baseURL: https://milestofreedom.netlify.app/
languageCode: en-us
summaryLength: '10'
theme: kross-hugo
title: Miles To Freedom
params:
  address: Nairobi, Kenya
  author: Abel MOgambi
  contact:
    enable: yes
    form_action: '#'
  cookies:
    enable: yes
    expire_days: 2
  copyright: Copyright &copy; 2021 a theme by [gethugothemes](https://gethugothemes.com)
  description: This is meta description
  email: fmogambi77@email.com
  google_analytics_id: ''
  home: Home
  logo: ''
  map:
    enable: yes
    gmap_api: https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  phone: +880 2544 658 256
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/google-map/map.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - URL: '#'
      icon: ti-facebook
    - URL: '#'
      icon: ti-instagram
    - URL: '#'
      icon: ti-dribbble
    - URL: '#'
      icon: ti-twitter-alt
  theme_color: '#FFBF00'
menu:
  main:
    - URL: about
      name: About
      weight: 1
    - URL: blog
      name: Blog
      weight: 2
    - URL: portfolio
      name: Portfolio
      weight: 3
    - URL: contact
      name: Contact
      weight: 4
